Repository prooph/proophessor-do, pull requests merged in 2018-04, with the labels that each got.

#163 Update docker-compose.yml
  docker-compose.yml
Labels: enhancement

#164 Update snapshots.md
  docs/installation/snapshots.md
Labels: bug

#165 Fix reset projections and add replay script
  scripts/history_replay.php
  src/Projection/Todo/TodoReadModel.php
  src/Projection/Todo/TodoReminderReadModel.php
  src/Projection/User/UserReadModel.php
Labels: bug, enhancement

#166 split into todo- & user-stream
  Vagrantfile
  bin/todo_projection.php
  bin/todo_reminder_projection.php
  bin/todo_snapshotter.php
  bin/user_projection.php
  bin/user_snapshotter.php
  config/autoload/prooph.global.php
  docs/installation/docker.md
  scripts/create_event_streams.php
Labels: enhancement
